export const data = {
  name: "Saif Hamdare",
  mobileNumber: 9004659899,
  emailId: "saifhamdare@gmail.com",
  linkedIn: "linkedin",
  portFolio: "portfolio",
  summary:
    "FrontEnd Developer with a Experience of 1.6 Year Specialized in ReactJS",
  education: "Bachelor of Science in Information Technology",
  educationAbbrivation: "BscIT",
  university: "Mumbai University",
  batch:2019,
  skills: [
    { id: "1", name: "ReactJS", icon: "" },
    { id: "2", name: "Redux Toolkit", icon: "" },
    { id: "3", name: "JavaScript", icon: "" },
    { id: "4", name: "HTML5", icon: "" },
    { id: "5", name: "CSS3", icon: "" },
    { id: "6", name: "SCSS", icon: "" },
    { id: "7", name: "Bootstrap", icon: "" },
    { id: "8", name: "AntDesign", icon: "" },
    { id: "9", name: "MUI / Material UI", icon: "" },
    { id: "10", name: "TailwindCSS", icon: "" },
    { id: "11", name: "git / GitHub", icon: "" },
  ],
  organizations: [
    {
      id: "3    ",
      name: "PolicyGuru Pvt Ltd.",
      description: [],
      designaiton:"Software Engineer 1",
      location: "Mumbai",
      startDate: "December 2022",
      endDate: "present",
      logo: "",
    },
    {
      id: "2",
      name: "ImpactGuru Technology Ventures",
      description: [],
      designaiton:"FrontEnd Developer Intern",
      location: "Mumbai",
      startDate: "September 2022",
      endDate: "December 2022",
      logo: "",
    },
    {
      id: "1",
      name: "Nestable pvt ltd",
      description: [],
      designaiton:"Associate Web Developer ",
      location: "Mumbai",
      startDate: "March 2022",
      endDate: "Junwe 2022",
      logo: "",
    },
  ],
};
